import { useEffect, useRef, useState } from 'react';
import { FreeResponse } from './FreeResponse';
import { calculateEstimate, emptyFinancialState, formatMoney, newProcedure, type Estimate, type FinancialState, type Procedure } from './financeApi';

type Props = { initial: FinancialState | null; initialResult?: Estimate | null; initialView?: 'cost' | 'schedule'; onDraft?: (state: FinancialState) => void; onConfirm: (state: FinancialState | null, result?: Estimate | null) => void; onAsk: (message: string, state: FinancialState | null, draft: FinancialState) => void; busy?: boolean };
const numeric = (value: string) => value.trim() === '' ? null : Number(value);
function Amount({ label, value, onChange, percent = false }: { label: string; value: number | null; onChange: (value: number | null) => void; percent?: boolean }) {
  return <label className="finance-field"><span>{label}{percent ? ' (%)' : ' (USD)'}</span><input type="number" inputMode="decimal" min="0" max={percent ? 100 : 1000000} step={percent ? '0.1' : '0.01'} value={value ?? ''} placeholder="Not sure" onChange={event => onChange(numeric(event.target.value))} /></label>;
}
function DateField({ label, value, onChange }: { label: string; value: string | null; onChange: (value: string | null) => void }) { return <label className="finance-field"><span>{label}</span><input type="date" value={value || ''} onChange={event => onChange(event.target.value || null)} /></label>; }
function BooleanField({ label, value, onChange }: { label: string; value: boolean | null; onChange: (value: boolean | null) => void }) { return <label className="finance-field"><span>{label}</span><select value={value === null ? 'unknown' : String(value)} onChange={event => onChange(event.target.value === 'unknown' ? null : event.target.value === 'true')}><option value="unknown">Not sure</option><option value="true">Yes</option><option value="false">No</option></select></label>; }

function Result({ result }: { result: Estimate }) {
  const { calculation } = result;
  const clinicOnly = calculation.rows.every(row => row.status === 'clinic_estimate');
  return <div className="cost-result" aria-live="polite">
    <div className="cost-totals"><div><span>{calculation.totalPatientPays === null ? 'Your total needs more details' : clinicOnly ? 'Clinic’s estimate of your share' : 'You may pay'}</span><strong>{formatMoney(calculation.totalPatientPays)}</strong>{calculation.status === 'conditional' && !clinicOnly && <small>Based on the assumptions below</small>}</div><div><span>Your plan may pay</span><strong>{formatMoney(calculation.totalInsurerPays)}</strong></div></div>
    <div className="cost-rows">{calculation.rows.map(row => <article className="cost-row" key={row.id}><div><h4>{row.name}</h4><p>{row.date || 'Using your current plan details'} · {row.status === 'clinic_estimate' ? 'From your clinic' : row.status === 'incomplete' ? 'Still needs a detail' : 'Estimate to confirm'}</p></div><dl><div><dt>{row.quoteType === 'patient_estimate' ? 'Clinic says you pay' : 'Dentist’s price'}</dt><dd>{formatMoney(row.quotedFee)}</dd></div>{row.quoteType !== 'patient_estimate' && <><div><dt>You pay first</dt><dd>{formatMoney(row.deductible)}</dd></div><div><dt>Your plan pays</dt><dd>{formatMoney(row.insurerPays)}</dd></div></>}<div><dt>You may pay</dt><dd>{formatMoney(row.patientPays)}</dd></div></dl>
      {row.quoteType === 'patient_estimate' ? <p className="cost-explanation">The clinic has already estimated your share after insurance. We have kept that amount as supplied.</p> : result.state.procedures.find(p => p.id === row.id)?.covered === false ? <p className="cost-explanation">Your plan does not cover this treatment under the details supplied, so you pay the dentist’s price.</p> : row.deductible !== null && row.insurancePercent !== null && row.insurerPays !== null && row.patientPays !== null ? <p className="cost-explanation">{row.deductible > 0 ? `You pay the first ${formatMoney(row.deductible)} yourself. ` : 'No amount is paid first for this treatment. '}{row.insurancePercent === 0 ? 'Your plan pays no share of the covered price.' : `Your plan pays ${row.insurancePercent}% of the price it covers after that.`} {row.benefitCapApplied ? 'Its payment is limited by how much it can still pay this year. ' : ''}That leaves {formatMoney(row.patientPays)} for you.</p> : null}
      {row.eligibleFee !== null && row.quotedFee !== null && row.eligibleFee !== row.quotedFee && <p className="finance-note">Your plan works out its share using {formatMoney(row.eligibleFee)}, rather than the full quoted price.</p>}
      {row.quoteType === 'total_fee' && row.clinicPatientEstimate !== null && row.clinicPatientEstimate !== undefined && <p className="finance-note">Your clinic estimated {formatMoney(row.clinicPatientEstimate)} for you. Ask it to explain any difference from this breakdown.</p>}
      {row.gaps.length > 0 && <p className="finance-note">{row.gaps[0]}</p>}
    </article>)}</div>
    {calculation.warnings.length > 0 && <div className="cost-checks"><h4>What could change this estimate</h4><ul>{calculation.warnings.slice(0, 2).map(warning => <li key={warning}>{warning}</li>)}</ul>{calculation.warnings.length > 2 && <details className="finance-details"><summary>See other details to check</summary><ul>{calculation.warnings.slice(2).map(warning => <li key={warning}>{warning}</li>)}</ul></details>}</div>}
    <details className="finance-details"><summary>How much of your yearly plan money this uses</summary><p className="finance-note">These are planned payments, not bills your plan has already paid.</p>{calculation.benefitUsage.map(usage => <div className="usage-row" key={usage.period}><span>{usage.period === 'current' ? 'This plan year' : 'Next plan year'}</span><span>Plan pays: {formatMoney(usage.plannedInsurerPayment)}</span><span>Left afterward: {formatMoney(usage.remainingBenefit)}</span></div>)}</details>
  </div>;
}

export function FinancialWorkspace({ initial, initialResult, initialView, onDraft, onConfirm, onAsk, busy: consultationBusy = false }: Props) {
  const [state, setState] = useState<FinancialState>(() => structuredClone(initial || emptyFinancialState));
  const [tab, setTab] = useState<'cost' | 'schedule'>(initialView || 'cost');
  const [confirmed, setConfirmed] = useState(!!initialResult); const budget = state.budget ?? initialResult?.budget ?? null;
  const [result, setResult] = useState<Estimate | null>(initialResult || null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState(''); const [listening, setListening] = useState(false);
  const estimateAbort = useRef<AbortController | null>(null);
  const automaticDates = useRef(!!initialResult);
  useEffect(() => () => { estimateAbort.current?.abort(); }, []);
  function change(next: FinancialState, preserveDateConfirmation = false) { estimateAbort.current?.abort(); setBusy(false); setState(next); setResult(null); setError(''); setConfirmed(false); if (!preserveDateConfirmation) automaticDates.current = false; onConfirm(null); onDraft?.({ ...next, procedures: next.procedures.map(p => ({ ...p, name: p.name || 'Unspecified procedure' })) }); }
  function updatePlan(key: keyof FinancialState['plan'], value: number | string | boolean | null) { change({ ...state, plan: { ...state.plan, [key]: value } }); }
  function updateProcedure(id: string, patch: Partial<Procedure>) {
    const next = { ...state, procedures: state.procedures.map(p => p.id === id ? { ...p, ...patch } : p) };
    const recalculateDate = Object.keys(patch).every(key => key === 'date') && automaticDates.current;
    change(next, recalculateDate);
    if (recalculateDate) void calculate(next);
  }
  async function calculate(next = state) {
    const controller = new AbortController(); estimateAbort.current?.abort(); estimateAbort.current = controller; setBusy(true); setError('');
    try { const output = await calculateEstimate(next, budget, controller.signal); if (!controller.signal.aborted) { setResult(output); setState(output.state); setConfirmed(true); automaticDates.current = true; onConfirm(output.state, output); } }
    catch (err) { if (!controller.signal.aborted) setError(err instanceof Error ? err.message : 'The estimate could not complete.'); }
    finally { if (estimateAbort.current === controller) setBusy(false); }
  }
  function downloadReminder() {
    if (!state.plan.benefitYearEnd) return;
    const date = new Date(`${state.plan.benefitYearEnd}T12:00:00Z`); date.setUTCDate(date.getUTCDate() - 14);
    const stamp = date.toISOString().slice(0, 10).replaceAll('-', '');
    const contents = ['BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//PlanPilot//Benefits reminder//EN', 'BEGIN:VEVENT', `UID:planpilot-${Date.now()}@local`, `DTSTAMP:${new Date().toISOString().replace(/[-:]/g, '').replace(/\.\d{3}/, '')}`, `DTSTART;VALUE=DATE:${stamp}`, 'SUMMARY:Review your dental benefits before renewal', 'DESCRIPTION:Check remaining benefits and discuss necessary care with your dentist. No treatment details are included.', 'END:VEVENT', 'END:VCALENDAR', ''].join('\r\n');
    const url = URL.createObjectURL(new Blob([contents], { type: 'text/calendar' })); const link = document.createElement('a'); link.href = url; link.download = 'PlanPilot-benefit-reminder.ics'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  return <section className="financial-workspace" aria-label="Your cost and options"><div className="finance-intro"><div><p className="journey-context">YOUR BILL, EXPLAINED</p><h3>Your cost, made clear.</h3></div><span>USD · Estimates to verify</span></div>
    <div className="finance-tabs" role="tablist" aria-label="Planning tools">{([['cost', 'Your quote'], ['schedule', 'Treatment dates']] as const).map(([value, label]) => <button key={value} role="tab" aria-selected={tab === value} onClick={() => setTab(value)}>{label}</button>)}</div>
    <div role="tabpanel" aria-label={tab === 'cost' ? 'Your quote' : 'Treatment dates'}>
    {tab === 'cost' && <><p className="finance-note">Check the prices and plan details Bili found. Not sure about something? Leave it blank and ask Bili below.</p>{result && <Result result={result} />}<details className="finance-input-review" open={!result}><summary>{result ? 'Change your quote or coverage inputs' : 'Check your bill and plan details'}</summary><div className="finance-fields plan-fields"><Amount label="Still to pay before your plan helps" value={state.plan.remainingDeductible} onChange={value => updatePlan('remainingDeductible', value)} /><Amount label="Your plan can still pay this year" value={state.plan.remainingBenefit} onChange={value => updatePlan('remainingBenefit', value)} /></div>
      <details className="finance-details"><summary>Your yearly allowance</summary><div className="finance-fields"><Amount label="Most your plan pays per year" value={state.plan.annualMaximum} onChange={value => updatePlan('annualMaximum', value)} /><Amount label="Yearly amount you pay first" value={state.plan.annualDeductible} onChange={value => updatePlan('annualDeductible', value)} /></div>{state.plan.annualMaximum !== null && state.plan.remainingBenefit !== null && <p className="finance-note">Reported benefits used: {formatMoney(Math.max(0, state.plan.annualMaximum - state.plan.remainingBenefit))}. This uses your reported balances, not insurer claims records.</p>}</details>
      {state.procedures.map(p => <article className="procedure-editor" key={p.id}><div className="procedure-heading"><label className="finance-field"><span>Procedure name</span><input value={p.name} placeholder="Procedure from your dentist" onChange={event => updateProcedure(p.id, { name: event.target.value })} /></label><button className="text-button" onClick={() => change({ ...state, procedures: state.procedures.filter(other => other.id !== p.id).map(other => ({ ...other, dependsOn: other.dependsOn.filter(id => id !== p.id) })) })}>Remove</button></div><div className="finance-fields"><Amount label={`Dentist quote for ${p.name || 'procedure'}`} value={p.quote} onChange={value => updateProcedure(p.id, { quote: value })} /><label className="finance-field"><span>What does this amount represent?</span><select value={p.quoteType} onChange={event => updateProcedure(p.id, { quoteType: event.target.value as Procedure['quoteType'] })}><option value="unknown">Not sure yet</option><option value="total_fee">Full fee before insurance</option><option value="patient_estimate">What the clinic expects me to pay</option></select></label><Amount label="Your plan pays" percent value={p.insurancePercent} onChange={value => updateProcedure(p.id, { insurancePercent: value })} /></div>
        <details className="finance-details"><summary>Other details that may change your cost</summary><div className="finance-fields"><BooleanField label="Your plan covers this treatment now" value={p.covered} onChange={value => updateProcedure(p.id, { covered: value })} /><BooleanField label="You pay an amount first for this treatment" value={p.deductibleApplies} onChange={value => updateProcedure(p.id, { deductibleApplies: value })} /><label className="finance-field"><span>Does your dentist have agreed prices with your plan?</span><select value={p.network} onChange={event => updateProcedure(p.id, { network: event.target.value as Procedure['network'] })}><option value="unknown">Not confirmed</option><option value="in">Yes, agreed prices with my plan</option><option value="out">No agreed prices with my plan</option></select></label><Amount label="Clinic patient estimate (if provided)" value={p.clinicPatientEstimate ?? null} onChange={value => updateProcedure(p.id, { clinicPatientEstimate: value })} /><Amount label="Price your plan uses for this treatment" value={p.allowedAmount} onChange={value => updateProcedure(p.id, { allowedAmount: value })} /><label className="finance-field"><span>Which price does your plan use?</span><select value={p.feeBasis} onChange={event => updateProcedure(p.id, { feeBasis: event.target.value as Procedure['feeBasis'] })}><option value="unknown">Not sure yet</option><option value="quoted_fee">The dentist’s full price</option><option value="allowed_amount">A different agreed price</option></select></label><label className="finance-field"><span>Procedure code (optional)</span><input value={p.code || ''} onChange={event => updateProcedure(p.id, { code: event.target.value || null })} /></label></div></details></article>)}
      {state.procedures.length < 8 && <button className="text-button" onClick={() => { const p = newProcedure(); change({ ...state, procedures: [...state.procedures, p] }); }}>Add another procedure</button>}
      <label className="finance-check"><input type="checkbox" checked={confirmed} onChange={event => { setConfirmed(event.target.checked); if (!event.target.checked) automaticDates.current = false; if (!event.target.checked) { setResult(null); onConfirm(null); } }} />I’ve checked these details. Missing details stay unknown.</label><button className="primary" disabled={!confirmed || busy || !state.procedures.length} onClick={() => void calculate()}>{busy ? 'Calculating…' : 'Calculate my personal cost'}</button>{error && <p className="form-error" role="alert">{error}</p>}</details></>}
    {tab === 'schedule' && <><p className="finance-note">Explore dates your dentist has approved. See whether treatment before or after your yearly allowance resets changes your share.</p><div className="finance-fields"><DateField label="Your yearly plan starts" value={state.plan.benefitYearStart} onChange={value => updatePlan('benefitYearStart', value)} /><DateField label="Your yearly plan ends" value={state.plan.benefitYearEnd} onChange={value => updatePlan('benefitYearEnd', value)} /><Amount label="Most your plan pays next year" value={state.plan.nextYearAnnualMaximum} onChange={value => updatePlan('nextYearAnnualMaximum', value)} /><Amount label="Amount you pay first next year" value={state.plan.nextYearDeductible} onChange={value => updatePlan('nextYearDeductible', value)} /></div><label className="finance-check"><input type="checkbox" checked={state.plan.renewalConfirmed} onChange={event => updatePlan('renewalConfirmed', event.target.checked)} />I confirmed renewal uses these benefits and the same coverage rules</label>
      {state.procedures.map(p => <article className="schedule-item" key={p.id}><h4>{p.name || 'Unnamed procedure'}</h4><div className="finance-fields"><DateField label={`Planned date for ${p.name}`} value={p.date} onChange={value => updateProcedure(p.id, { date: value })} /><DateField label="Dentist-approved earliest date" value={p.earliestDate} onChange={value => updateProcedure(p.id, { earliestDate: value })} /><DateField label="Dentist-approved latest date" value={p.latestDate} onChange={value => updateProcedure(p.id, { latestDate: value })} /></div><label className="finance-check"><input type="checkbox" checked={p.dentistApprovedWindow} onChange={event => updateProcedure(p.id, { dentistApprovedWindow: event.target.checked })} />My dentist approved this date window</label><details className="finance-details"><summary>Required preceding treatments</summary>{state.procedures.filter(other => other.id !== p.id).map(other => <label className="finance-check" key={other.id}><input type="checkbox" checked={p.dependsOn.includes(other.id)} onChange={event => updateProcedure(p.id, { dependsOn: event.target.checked ? [...p.dependsOn, other.id] : p.dependsOn.filter(id => id !== other.id) })} />{other.name || 'Unnamed procedure'}</label>)}</details></article>)}
      <label className="finance-check"><input type="checkbox" checked={confirmed} onChange={event => { setConfirmed(event.target.checked); if (!event.target.checked) automaticDates.current = false; }} />I’ve checked these plan details and dates</label><button className="primary" disabled={!confirmed || busy || !state.procedures.length} onClick={() => void calculate()}>{busy ? 'Recalculating…' : 'Recalculate and compare dates'}</button>{error && <p className="form-error" role="alert">{error}</p>}{result && <><Result result={result} /><div className="schedule-comparison"><h4>{result.optimization.available ? 'Your schedule comparison' : 'Before we compare dates'}</h4><p>{result.optimization.reason}</p>{result.optimization.available && <><div className="cost-totals"><div><span>Original personal cost</span><strong>{formatMoney(result.optimization.original.totalPatientPays)}</strong></div><div><span>Lowest evaluated cost</span><strong>{formatMoney(result.optimization.best?.totalPatientPays ?? null)}</strong></div><div><span>Potential difference</span><strong>{formatMoney(result.optimization.savings)}</strong></div></div><ul>{result.optimization.dates.map(d => <li key={d.id}>{state.procedures.find(p => p.id === d.id)?.name}: {d.date}</li>)}</ul><button className="voice-button" onClick={() => { const next = { ...state, procedures: state.procedures.map(p => ({ ...p, date: result.optimization.dates.find(d => d.id === p.id)?.date || p.date })) }; change(next); void calculate(next); }}>Use these approved dates</button></>}</div></>}{state.plan.benefitYearEnd && <button className="text-button" onClick={downloadReminder}>Download a calendar reminder before benefits expire</button>}</>}
    </div>
    <div className="finance-followup"><h4>Keep planning with Bili</h4><div className="finance-suggestions"><button className="text-button" onClick={() => setMessage('Explain the breakdown of my estimate.')}>Explain my estimate</button><button className="text-button" onClick={() => setMessage('Help me find the missing coverage details.')}>Help with missing details</button></div><FreeResponse id="finance-message" label="Tell Bili a correction, quote, or question" placeholder="Type or speak a quote, correction, or question…" value={message} onChange={setMessage} onListeningChange={setListening} /><button className="voice-button" disabled={!message.trim() || listening || consultationBusy || busy} onClick={() => onAsk(message.trim(), result ? state : null, state)}>Continue with Bili</button><p className="finance-note">Corrections and newly extracted quotes return for your review before calculation. Estimates are not insurer-approved payments.</p></div>
  </section>;
}
