import type { Profile, Snapshot } from './accountApi';
import { CapturedDetails } from './CapturedDetails';
import { formatMoney } from './financeApi';

export function OverviewPage({ profile, snapshot, onContinue }: { profile: Profile; snapshot: Snapshot | null; onContinue: () => void }) {
  const result = snapshot?.financialState ? snapshot.financialResult : null;
  const turn = snapshot?.turn;
  const captured = [...new Map([...(snapshot?.history.flatMap(entry => entry.turn.facts) || []), ...(turn?.facts || [])].map(fact => [fact.label, fact])).values()];
  const coverageTurn = turn ? { ...turn, facts: captured } : null;
  const ready = turn?.kind === 'ready';
  return <main className="account-page overview-page">
    <div className="page-heading"><div><p className="eyebrow"><span /> YOUR BENEFITS, IN FOCUS</p><h1>Welcome back, {profile.name.split(' ')[0]}.</h1><p>{turn ? 'Your insurance story, right where you left it.' : 'A little clarity starts with your plan.'}</p></div><button className="voice-button" onClick={onContinue}>{snapshot ? 'Continue with Bili' : 'Begin my journey'}<span aria-hidden="true">→</span></button></div>
    {!turn ? <section className="overview-empty"><div className="empty-landscape" /><div><p className="journey-context">Your next clear step</p><h2>Let’s make sense<br />of your dental benefits.</h2><p>Bili will help you understand your insurance, read a dentist’s estimate, and see what you may pay.</p><button className="primary" onClick={onContinue}>{snapshot?.answers.length ? 'Resume my journey' : 'Start My Plan'}<span aria-hidden="true">→</span></button><small>Your insurance details will appear here as you share them.</small></div></section> : <>
      <section className="overview-banner"><div><span className="status-pill">{ready ? 'Your planning summary' : 'Journey in progress'}</span><h2>{ready ? turn.title : 'Every detail brings a little more clarity.'}</h2><p>{ready ? turn.context : 'You can return to your last question whenever you’re ready.'}</p></div><button className="primary" onClick={onContinue}>{ready ? 'Review My Plan' : 'Pick up where I left off'}<span aria-hidden="true">→</span></button></section>
      {result && <section className="overview-metrics" aria-label="Your cost estimate"><article className="metric-card featured"><span>Estimated amount you pay</span><strong>{formatMoney(result.calculation.totalPatientPays)}</strong><small>{result.calculation.totalPatientPays === null ? 'A few details are still needed.' : 'Based on the details you reviewed.'}</small></article><article className="metric-card"><span>Estimated insurance contribution</span><strong>{formatMoney(result.calculation.totalInsurerPays)}</strong><small>Planned payments, before an insurer confirms them.</small></article><article className="metric-card"><span>Benefits available before treatment</span><strong>{formatMoney(snapshot!.financialState!.plan.remainingBenefit)}</strong><small>From your reviewed plan information.</small></article></section>}
      <div className="overview-columns"><section className="overview-coverage"><p className="section-caption">WHAT WE KNOW</p><CapturedDetails turn={coverageTurn!} /><button className="text-button" onClick={onContinue}>Review or correct these details <span aria-hidden="true">→</span></button></section><section className="next-step-card"><p className="section-caption">YOUR NEXT MOVES</p><h2>{ready ? 'A clear way forward.' : 'We’ll take it one question at a time.'}</h2>{turn.actions.length ? <ol>{turn.actions.map((action, index) => <li key={index}>{action}</li>)}</ol> : <p>Continue with Bili to fill in what matters for your goal.</p>}{snapshot!.documentNames.length > 0 && <p className="finance-note">Documents shared: {snapshot!.documentNames.join(', ')}. Your answers and extracted details are saved; the original files aren’t stored.</p>}</section></div>
      {result && <section className="overview-breakdown"><div className="section-heading"><h2>Your treatment costs</h2><span>Estimates · USD</span></div><div className="cost-rows">{result.calculation.rows.map(row => <article className="cost-row" key={row.id}><h4>{row.name}</h4><dl><div><dt>Dentist’s quoted total</dt><dd>{formatMoney(row.quotedFee)}</dd></div><div><dt>Insurance may pay</dt><dd>{formatMoney(row.insurerPays)}</dd></div><div><dt>You pay before sharing costs</dt><dd>{formatMoney(row.deductible)}</dd></div><div><dt>Your estimated share</dt><dd>{formatMoney(row.patientPays)}</dd></div></dl>{row.quoteType === 'patient_estimate' && <p className="finance-note">This is the clinic’s estimate of your share. Insurance hasn’t been subtracted again.</p>}{row.gaps.length > 0 && <p className="finance-note">Still needed: {row.gaps.join(' ')}</p>}</article>)}</div>{result.calculation.warnings.length > 0 && <details className="finance-details"><summary>What could change this estimate?</summary><ul>{result.calculation.warnings.map((warning, i) => <li key={i}>{warning}</li>)}</ul></details>}<p className="finance-note">Confirm coverage with your insurer and treatment dates with your dentist before deciding.</p></section>}
    </>}
  </main>;
}
